### ISSUE TITLE
WN19-UR-000020 - Null Value Breaks Control

### ISSUE THREAD

**Issue by kclinden** [ansible-lockdown/Windows-2019-STIG#12]
When trying to run task WN19-UR-000020 it fails since it is not given a value. The value should be changed to ""

**Error**
```
TASK [Windows-2019-STIG : HIGH | WN19-UR-000020 | Windows Server 2019 Act as part of the operating system user right must not be assigned to any groups or accounts.] *******************************
task path: /Users/kclinden/.ansible/roles/Windows-2019-STIG/tasks/cat1.yml:353
redirecting (type: modules) ansible.builtin.win_user_right to ansible.windows.win_user_right
Using module file /Users/kclinden/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_user_right.ps1
Pipelining is enabled.
<192.168.67.8> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5985 TO 192.168.67.8
EXEC (via pipeline wrapper)
The full traceback is:
Cannot bind argument to parameter 'InputObject' because it is an empty string.
At line:346 char:34
+ $userSids = [String[]]@($users | ConvertTo-SecurityIdentifier | ForEa ...
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-SecurityIdentifier], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,ConvertTo-SecurityIdentifier

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 346

System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'InputObject' because it is an empty string.
   at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
   at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStateInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
   at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingState(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
   at System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject inputToOperateOn)
   at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject inputToOperateOn)
   at System.Management.Automation.CommandProcessor.Read()
fatal: [w2019-test]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Cannot bind argument to parameter 'InputObject' because it is an empty string."
```

**Code**
```yaml
- name: "HIGH | WN19-UR-000020 | Windows Server 2019 Act as part of the operating system user right must not be assigned to any groups or accounts."
  win_user_right:
    name: SeTcbPrivilege
    users: 
    action: set
  when: wn19_ur_000020
  tags:
      - WN19-UR-000020
      - V-93051
      - SRG-OS-000324-GPOS-00125
      - SV-103139r1
      - CCI-002235
      - patch
      - high
```

**Comment by georgenalen** [comment]
kclinden,
 I have merged the changes into devel, however I want to hear if things are looking better on your side since I did modify what you had. You changed the user value from blank to double quotes. With double quotes that control was failing in AWS and tests locally in Vagrant. Looking deeper into the module involved it looks like we should be using [] instead of quotes. 

 I made the change over to brackets and it worked both locally and via the testing pipeline. I also brought that control out of compliance manually on a local test machine, then ran the role against it watching control WN19-UR-000020 remove all users from the Act as part of the operating system user section. So it looks like it's fixed an runs

 I only have that fix in devel right now, if I get confirmation that it looks better on your end or if a couple days go by without hearing anything I will merge the changes over to the main branch. 

 I also updated the readme and contributing file with that merge as well

George
